<?php
return $en = array(
    //Relativo à navbar
    "NAV_Sistemas" => "Systems",
    "NAV_Sobre" => "About",
    "NAV_Entrar" => "Login",
    "NAV_Registar" => "Register",
    "NAV_Eventos" => "Events",
    "LinguagemEN" => "English",
    "LinguagemPT" => "Portuguese",
    "DropdownLinguagem" => "Language",
    "NAV_Organizacao" => "Organization",
    "NAV_Profile" => "Profile",
    "NAV_Leave" => "Leave",
    //Relativo aos sistemas
    "TituloSistemas" => "Systems",
    "BTN_CriarSistema" => "Create new System",
    "SistemaCriadoPor" => "Made by: ",
    //Sistema
    "BTN_ReturnListaSistemas" => "Return to system list",
    "TituloSistema" => "Planets from ",
    "BTN_AdicionarPlaneta" => "Add Planet",
    "BTN_AdicionarAsteroide" => "Add Asteroid",
    "BTN_EditarSistema" => "Edit System",
    "BTN_ApagarSistema" => "Delete System",
    "BTN_PerguntasPlaneta" => "Questions",
    "BTN_Editar" => "Edit",
    "BTN_Apagar" => "Delete",
    //Registo
    "TituloCriarConta" => "Create new account",
    "LabelNome" => "Full Name",
    "LabelEmail" => "Email Address",
    "LabelNomeUtilizador" => "Username",
    "LabelPassword" => "Password",
    "LabelConfirmarPassword" => "Confirm your password",
    "BTN_Registar" => "Register",
    "PlaceholderNome" => "Insert your full name",
    "PlaceholderUsername" => "Insert your username",
    "PlaceholderEmail" => "Insert your email address",
    "PlaceholderPassword" => "Insert your password",
    "PlaceholderConfirmPassword" => "Insert your password again",
    "EmailH1" => "Welcome to PlanetarySystemGO",
    "EmailSubject" => "PlanetarySystemGO account verification",
    "EmailFirstLine" => "To be able to use every service in our system, you will have to verify your account.",
    "EmailSecondLine" => "To do that, click",
    "EmailHyperLink" => "here",
    "ErrorEmail" => "An error occurred. Please try again later",
    "EmailAlreadyExists" => "The email address is already registered!",
    "SuccessfullyAuth" => "Successfully registered!",
    "InvalidEmail" => "The email address is not valid!",
    "NonCoincidentPasswords" => "Passwords do not match!",
    "BTN_ReturnIndex" => "Go to home page",
    "OversidedName" => "The name is too big!",
    //Login
    "BTN_Login" => "Login",
    "EntrarTitulo" => "Login",
    //Lista de Eventos
    "TituloListaEventos" => "Events",
    "BTN_CriarEvento" => "Create New Event",
    //Editar planeta e Detalhes Planeta
    "TitleEditarPlaneta" => "Edit Planet",
    "TituloAdicionarPlaneta" => "Add Planet",
    "LabelNomePlaneta" => "Planet's Name",
    "LabelDescriçãoPlaneta" => "Planet's Description",
    "LabelTamanhoPlaneta" => "Planet Size",
    "LabelVelocidadePlaneta" => "Planet's speed",
    "LabelVelocidadeRotacaoPlaneta" => "Planet's Rotation Speed",
    "LabelImagemPlaneta" => "Planet's Image",
    "LabelTexturaPlaneta" => "Planet's Texture",
    "LabelFoco1ElipsePlaneta" => "First Focus of the Ellipse of the Planet",
    "LabelFoco2ElipsePlaneta" => "Second Focus of the Ellipse of the Planet",
    "LabelDistanciaFoco1ElipseOrbita" => "Distance from the First Focus of the Planet's Orbit",
    "LabelDistanciaFoco2ElipseOrbita" => "Distance from the Second Focus of the Planet's Orbit",
    "PlaceholderNomePlaneta" => "Insert the planet's name",
    "PlaceholderDescriçãoPlaneta" => "Insert the planet's description",
    "PlaceholderTamanhoPlaneta" => "Insert the planet's size",
    "PlaceholderVelocidadePlaneta" => "Insert the planet's speed",
    "PlaceholderVelocidadeRotaçãoPlaneta" => "Insert the planet's rotation speed",
    "PlaceholderDistanciaFoco1ElipseOrbita" => "Insert the distance from the first focus of the planet's orbit",
    "PlaceholderDistanciaFoco3ElipseOrbita" => "Insert the distance from the first focus of the asteroid's orbit",
    "PlaceholderDistanciaFoco2ElipseOrbita" => "Insert the distance from the second focus of the planet's orbit",
    "PlaceholderDistanciaFoco4ElipseOrbita" => "Insert the distance from the second focus of the asteroid's orbit",
    "PlaceholderFoco1ElipsePlaneta" => "Insert the first focus of the planet's ellipse",
    "PlaceholderFoco2ElipsePlaneta" => "Insert the second focus of the planet's ellipse",
    "BTN_InserirPlaneta" => "Insert Planet",
    "BTN_VoltarListaSistemas" => "Return to systems list",
    "BTN_EditarPlaneta" => "Edit Planet",
    "BTN_EditarAsteroid" => "Edit Asteroid",
    //Detalhes evento
    "BTN_VoltarListaEventos" => "Return to events list",
    "LabelNomeEvento" => "Event's name",
    "LabelLatitudeEvento" => "Latitude",
    "LabelLongitudeEvento" => "Longitude",
    "LabelDistânciaPlanetaLonge" => "Distance from the furthest planet",
    "LabelParticipaçõesEvento" => "Participations",
    "LabelNomeAluno" => "Student's name",
    "LabelPontos" => "Score",
    "LabelData" => "Date",
    "LabelTotalPontos" => "Total score",
    //Editar Eventos e Adicionar Eventos
    "TituloCriarEvento" => "Create Event",
    "TituloEditarEvento" => "Edit Event",
    "PlaceholderNomeEvento" => "Insert the event's name",
    "PlaceholderLatitudeEvento" => "Insert the latitude of the center of the event",
    "PlaceholderLongitudeEvento" => "Insert the longitude of the center of the event",
    "PlaceholderDistânciaPlanetaLonge" => "Insert the distance from the furthest planet",
    "BTN_EditarEvento" => "Edit Event",
    "LabelSistemaUsar" => "System to be used",
    "BTN_ParametrizarEvento" => "Parametrize Event",
    //Confirmação de email
    "LabelWelcome" => "Welcome,",
    "ConfirmParagrafo1" => "You need to verify your account.",
    "ConfirmParagrafo2" => "Please check your email and click on the verification",
    "ConfirmParagrafo3" => "link that we sent you to",
    "ConfirmParagrafo4" => "Didn't receive de confirmation email?",
    "ConfirmParagrafo5" => "To re-send the email, click on the button bellow",
    "HyperlinkSendEmail" => "Re-send Email",
    //Apagar planeta
    "AskDeletePlanet" => "Do you want to delete this planet?",
    "BTN_Return" => "Return",
    "BTN_DeletePlanet" => "Delete Planet",
    //Apagar Evento
    "AskDeleteEvent" => "Do you want to delete this event?",
    "BTN_DeleteEvent" => "Delete Event",
    //Sobre o jogo
    "TitleAboutGame" => "About the game",
    "AboutGameParagrafo1" => "The SolarSystemGo game aims to promote learning about the Solar System in a playful way, using an Augmented Reality (AR) application available on the mobile phone. In this game, students organized in teams of 3 to 4 students, start their journey on the Sun and the challenge is to find the orbits and their planets, answering questions about them. For each stage successfully completed, they receive points and the team with the most points wins the game.",
    "AboutGameParagrafo2" => "AR is an emerging topic that has been gaining prominence thanks to its great potential to combine the real world with virtual objects, which allows to capture the interest and attention of students in order to promote their learning.",
    "AboutGameParagrafo3" => "To be played, GPS is necessary, so it has to take place in an outer space away from buildings and other obstacles that may impair its use.",
    "AboutGameParagrafo4" => "The BackOffice aims to give teachers of the various educational degrees the possibility to customize this game according to the program they are teaching. In this sense, teachers can, for example, create the questions they consider appropriate to their level of education. teaching.",
    "AboutGameParagrafo5" => "SolarSystemGO carried out by students Miguel Silva, Rafael Lopes and Telmo Faria results from the continuation of a project that started in the academic year 2016/2017 (Carrança, 2017) in partnership with the Academy of Science, Art and Heritage.",
    "AboutGameReferencia" => "Reference:",
    "AboutGameTextoReferencia" => "J. A. Carrança, Tecnologias de Realidade Aumentada com Aplicação ao Ensino e Divulgação da Astronomia e da Paleontologia, Master Thesis (in portuguese), Instituto Politécnico de Tomar, 2017.",
    //Criar Sistema    
    "TituloAdicionarSistema" => "Add new system",
    "LabelNomeSistema" => "System's name",
    //Editar Sistema
    "TituloEditarSistema" => "Edit System",
    "LabelNovoNome" => "New name:",
    "DataValueRequired" => "Name is filling is mandatory!",
    //Apagar Sistema
    "LabelApagarSistema" => "Are you sure you want to delete this system?",
    "LabelCuidado" => "Careful! There are planets in this system!",
    //Lost Password
    "TituloLostPassword" => "Send email to restore password",
    "BTN_EnviarEmail" => "Send Email",
    "LabelForgotPassword" => "Forgot your password? Click",
    "AnchorHere" => "here",
    "TitleReporPassword" => "Reset your password",
    "LabelCantUpdatePassword" => "Your password could not be updated. Please try again later.",
    "LabelSuccessfullPasswordChange" => "Your password was changed successfully. Please log on to your account.",
    "LabelErrorPasswordChange" => "The link is invalid or your password has already been changed.",
    "LabelCantRecoverPassword" => "Can't recover your password at the moment. Please try again later.",
    "LabelEmailAlreadySent" => "The confirmation email was already sent.",
    "LabelMissingEmailDatabase" => "The entered email is not in the database.",
    "LabelEmailSendingError" => "There was an error sending the confirmation email. Please try again later.",
    "LabelEmailSentSuccessfully" => "Email successfully sent! Please go to your mailbox and click on the link we just sent you.",
    "EmailLostPasswordSubject" => "PlanetarySystemGO account recovery",
    "EmailLostP1" => "To change your PlanetarySystemGO password, click",
    "CantRecoverPW" => "Can't recover your password. Please try again later",
    "AlreadySentPW" => "An email was already sent.",
    "MessageChangesError" => "An error occured while sending the email.",
    "BadEmailProvided" => "The email you provided is invalid!",
    //Perguntas do Planeta
    "BTN_ReturnPlanetList" => "Return to list of Planets",
    "LabelAddQuestion" => "Add question",
    "LabelPerguntasPlaneta" => "Questions from planet: ",
    "LabelQuestion" => "Question",
    "LabelRespostaCorreta" => "Correct Answer",
    "BTN_Edit" => "Edit",
    "BTN_Delete" => "Delete",
    //Criar Pergunta
    "TitleAddQuestion" => "Add new question",
    "DataValueRequiredPergunta" => "Question is mandatory!",
    "LabelRespostas" => "Answers",
    "LabelRespostaCerta" => "Correct",
    "DataValueRequiredResposta" => "The right option is mandatory!",
    "BTN_ReturnListQuestions" => "Return to list of questions",
    "BTN_AddQuesion" => "Add",
    //Editar Pergunta
    "TitleEditQuestion" => "Edit Question",
    "QuestionActive" => "Active",
    "Save" => "Save",
    "GoBack" => "Exit",
    //Apagar Pergunta
    "LabelAskDelete" => "Do you really want to delete this question?",
    "LabelPerguntaSelecionada" => "Selected question:",
    "LavelConfirmarApagar" => "Delete",
    //Verificar
    "LabelRegistoComSucesso" => "Your account has been successfully verified. You can now log in and use all the features of the system.",
    "LabelRegistoSemSucesso" => "This account is invalid or it is already verified.",
    "LabelSemRegisto" => "An error has occurred. Please try again later.",
    //Repositorios
    "DefaultRepo" => "Choose a repository",
    "PrivRepo" => "Private",
    "AgrupRepo" => "School group",
    "PublicRepo" => "Public",
    "BTN_Clone" => "Clone",
    "BTN_Clone_Agrup" => "Clone to School Group",
    //myProfile
    "ChangePW" => "Change Password",
    "ChangeProfile" => "Change Profile",
    "Non-Existent" => "Non existent",
    "Alterar_Perfil" => "Submit Changes",
    "MessageChangesSuccess" => "Changes successfully made!",
    "MessageChangeError" => "An error occurred!",
    //Change Password
    "Alt_PW_CP" => "Current Password",
    "N_PW_CP" => "New Password",
    "C_PW_CP" => "Confirm New Password",
    //Organization
    "Non-Existent-Organization" => "Oops! Looks like you are not in an organization! Do you wish to create one?",
    "BTN_Create_Organization" => "Create Organization",
    "BTN_ShowSystems" => "Show organization's systems",
    "BTN_ShowMembers" => "Show organization's members",
    "BTN_InviteMembers" => "Invite users to the organization",
    "ButtonInviteToOrganization" => "Invite user",
    "TitleInvite" => "Invite",
    "PlaceholderInvite" => "Insert the email of the user you want to invite",
    "ErrorEmailNonExistant" => "The email provided doesn't exist in our system!",
    "ErrorAlreadyInOrganization" => "That user is already in an organization!",
    "EmailSuccessfullySent" => "The email was sent successfully!",
    "ErrorSendingEmail" => "An error ocurred while sending the email!",
    "InviteTitle" => "Invitation to the organization ",
    "InviteText1" => "The user ",
    "InviteText2" => " has invited you to join their organization.",
    "InviteText3" => "If you wish to accept, click ",
    "InviteText4" => " otherwise, ignore this email.",
    "BTN_RemoveMembers" => "Remove members from the organization",
    "LabelRemoveMember" => "Remove",
    "SuccessfullyRemoved" => "User successfully removed!",
    "ErrorRemoving" => "An error occurred while trying to remove the user",
    "NotAdmin" => "You are not an administrator!",
    "BTNEditOrganization" =>"Edit Organization",
    "AlreadyOrganizationError" => "You are already in an organization!",
    "InvitationAccepted" => "Invitation successfully accepted!",
    "InvitationError" => "An error occurred while trying to accept the invitation.",
    "OrganizationDeletedMessage" => "Organization deleted successfully!",
    "OrganizationDeleteFail" => "A problem occurred while trying to delete the organization.",
    "OrganizationDeleteQuestion" => "You are about to delete the organization. Are you sure you want to delete it?",
    "OrganizationEditButton" => "Edit Organization",
    "PlaceholderNomeAgrupamento" => "Insert the organization's name",
    "BTNDeleteOrganization" => "Delete Organization",
    "BTN_RETURN_DELETE_ORG" => "Return",
    //Pergunta
    "SelectCorrectQuestion" => "Please choose the correct answer",
    "OrganizationEditedMessage" => "Organization successfully edited!",
    "OrganizationNotEditedMessage" => "An error occurred while editing the organization. Please try again later.",
    "PlaceholderNewPassword" => "Insert your new password",
    "PlaceholderConfirmNewPassword" => "Insert your new password again",
    "ResetPasswordBTN" => "Reset Password",
    "LabelAdministração" => "Administration",
    "LabelListOfUsers" => "List of Users",
    "LabelListOfSystems" => "List of Systems",
    "LostPWSent" => "Email successfully sent!",
    "EventAlreadyExists" => "An event with the same name already exists!",
    "LabelRepositorioPublico" => "Public Repository",
    "LabelRepositorioPrivado" => "Private Repository",
    "LabelRepositorioOrganizacao" => "Organization's Repository",
    "DownloadAPKBTN" => "Download APK",
    "PlanetCreatedSuccessfully" => "Planet successfully created!",
    "PlanetNotCreated" => "An error occurred while creating a planet!",
    "AsteroidCreatedSuccessfully" => "Asteroid successfully created!",
    "AsteroidNotCreated" => "An error occurred while creating a asteroid!",
    "BTN_GráficosDoEvento" => "Event Graphs",
    "LabelListOfEvents" => "List of Events",
    //front-end
    "btn_moreRadius" => "Increase radius",
    "btn_lessRadius" => "Decrease radius",
    "btn_moreSpeed" => "Increase speed",
    "btn_lessSpeed" => "Decrease speed",
    "btn_moreSize" => "Increase size",
    "btn_lessSize" => "Decrease size",
    "btn_details" => "More details",
    "btn_changeCenter" => "Change center",
    "btn_Send" => "Acept system",
    "PlanetDeletedSuccessfully" => "Planet deleted",
    "PlanetNotDeleted" => "Planet not deleted",
    "PlaceholderNomeAsteroid" => "Insert the Asteroid Name",
    "LabelImagemAsteroid" => "Asteroid's Image",
    "LabelTexturaAsteroid" => "Asteroid's Texture",
    "PlaceholderDescriçãoAsteroid" => "Insert the asteroid's description",
    "PlaceholderTamanhoAsteroid" => "Insert the asteroid's size",
    "PlaceholderVelocidadeAsteroid" => "Insert the asteroid's speed",
    "PlaceholderVelocidadeRotaçãoAsteroid" => "Insert the asteroid's rotation speed",
    "BTN_InserirAsteroid" => "Insert Asteroid",
    //Criar Luas
    "PlaceholderNomeLuas" => "Insert the moon's name",
    "LabelImagemLuas" => "Moon's Image",
    "LabelTexturaLuas" => "Moon's Texture",
    "PlaceholderDescriçãoLuas" => "Insert the moon's description",
    "PlaceholderTamanhoLuas" => "Insert the moon's size",
    "PlaceholderVelocidadeLuas" => "Insert the moon's speed",
    "PlaceholderVelocidadeRotaçãoLuas" => "Insert the moon's rotation speed",
    "BTN_InserirLua" => "Insert Moon",
    "luasCreatedSuccessfully" => "Moon successfully created!",
    "luasNotCreated" => "An error occurred while creating a moon!",
    "BTN_EditarLua" => "Edit Moon",
    "BTN_ApagarLua" => "Delete Moon",
    "BTN_CriarLua" => "Create Moon",
    "LabelDistanciaFoco1ElipseOrbitamoon" => "Distance from the First Focus of the Moon's Orbit",
    "LabelDistanciaFoco2ElipseOrbitamoon" => "Distance from the Second Focus of the Moon's Orbit",
    "LuasDeletedSuccessfully" => "Moon deleted",
    "LuasNotDeleted" => "Moon not deleted",
    "AskDeleteMoon" => "Do you want to delete this moon?",
    //Perguntas Luas
    "BTN_PerguntaLua" => "Question about the moon",
    "LabelPerguntasLua" => "Questions from moon: ",
    "LabelAddQuestion" => "Add question",
    "PesquisarCorpoCeleste" => "Search Celestial Body",
    "Pesquisar" => "Search",
    "LimparPesquisa" => "Clean search",
    "LuasAssociadas" => "Associated Moons"
);