<?php
return $pt = array(
    //Relativo à navbar
    "NAV_Sistemas" => "Sistemas",
    "NAV_Sobre" => "Sobre",
    "NAV_Entrar" => "Entrar",
    "NAV_Registar" => "Registar",
    "NAV_Eventos" => "Eventos",
    "LinguagemEN" => "Inglês",
    "LinguagemPT" => "Português",
    "DropdownLinguagem" => "Linguagem",
    "NAV_Organizacao" => "Organização",
    "NAV_Profile" => "Perfil",
    "NAV_Leave" => "Sair",
    //Relativo à lista de sistemas
    "TituloSistemas" => "Sistemas",
    "BTN_CriarSistema" => "Criar novo Sistema",
    "SistemaCriadoPor" => "Criado por: ",
    //Sistema
    "BTN_ReturnListaSistemas" => "Voltar à lista de Sistemas",
    "TituloSistema" => "Planetas do ",
    "BTN_AdicionarPlaneta" => "Adicionar Planeta",
    "BTN_AdicionarAsteroide" => "Adicionar Asteroide",
    "BTN_EditarSistema" => "Editar Sistema",
    "BTN_ApagarSistema" => "Apagar Sistema",
    "BTN_PerguntasPlaneta" => "Perguntas",
    "BTN_Editar" => "Editar",
    "BTN_Apagar" => "Apagar",
    //Registo
    "TituloCriarConta" => "Criar nova conta",
    "LabelNome" => "Nome Completo",
    "LabelEmail" => "Endereço Email",
    "LabelNomeUtilizador" => "Nome de Utilizador",
    "LabelPassword" => "Password",
    "LabelConfirmarPassword" => "Confirme a sua password",
    "BTN_Registar" => "Registar",
    "PlaceholderNome" => "Insira o seu nome completo",
    "PlaceholderUsername" => "Insira o seu nome de utilizador",
    "PlaceholderEmail" => "Insira o seu endereço email",
    "PlaceholderPassword" => "Insira a sua password",
    "PlaceholderConfirmPassword" => "Insira novamente a sua password",
    "EmailH1" => "Bem-vindo ao PlanetarySystemGO",
    "EmailSubject" => "Verificação da conta do PlanetarySystemGO",
    "EmailFirstLine" => "Para poder utilizar todos os serviços do nosso sistema, terá de verificar a sua conta primeiro.",
    "EmailSecondLine" => "Para isso, terá de clicar",
    "EmailHyperLink" => "aqui",
    "ErrorEmail" => "Ocorreu um erro. Tente mais tarde",
    "EmailAlreadyExists" => "O endereço de email já está registado!",
    "SuccessfullyAuth" => "Registado com sucesso!",
    "InvalidEmail" => "Endereço de email não é válido!",
    "NonCoincidentPasswords" => "As passwords não coincidem!",
    "BTN_ReturnIndex" => "Ir para a página inicial",
    "OversidedName" => "O nome é demasiado grande!",
    //Login
    "BTN_Login" => "Autenticar",
    "EntrarTitulo" => "Entrar",
    //Lista de Eventos
    "TituloListaEventos" => "Eventos",
    "BTN_CriarEvento" => "Criar novo evento",
    //Editar planeta e adicionar planeta
    "TituloAdicionarPlaneta" => "Adicionar Planeta",
    "LabelNomePlaneta" => "Nome do Planeta",
    "LabelDescriçãoPlaneta" => "Descrição do planeta",
    "LabelTamanhoPlaneta" => "Tamanho do Planeta",
    "LabelVelocidadePlaneta" => "Velocidade do planeta",
    "LabelVelocidadeRotacaoPlaneta" => "Velocidade de rotação do planeta",
    "LabelImagemPlaneta" => "Imagem do planeta",
    "LabelTexturaPlaneta" => "Textura do planeta",
    "LabelFoco1ElipsePlaneta" => "Primeiro Foco da Elipse do Planeta",
    "LabelFoco2ElipsePlaneta" => "Segundo Foco da Elipse do Planeta",
    "LabelDistanciaFoco1ElipseOrbita" => "Distância do Primeiro Foco da Órbita do Planeta",
    "LabelDistanciaFoco2ElipseOrbita" => "Distância do Segundo Foco da Órbita do Planeta",
    "PlaceholderNomePlaneta" => "Insira o nome do planeta",
    "PlaceholderDescriçãoPlaneta" => "Insira a descrição do planeta",
    "PlaceholderTamanhoPlaneta" => "Insira o tamanho do planeta",
    "PlaceholderVelocidadePlaneta" => "Insira a velocidade do planeta",
    "PlaceholderVelocidadeRotaçãoPlaneta" => "Insira a velocidade de rotação do planeta",
    "PlaceholderDistanciaFoco1ElipseOrbita" => "Insira a distância do primeiro foco da órbita do planeta",
    "PlaceholderDistanciaFoco3ElipseOrbita" => "Insira a distância do primeiro foco da órbita do asteróide",
    "PlaceholderDistanciaFoco2ElipseOrbita" => "Insira a distância do segundo foco da órbita do planeta",
    "PlaceholderDistanciaFoco4ElipseOrbita" => "Insira a distância do segundo foco da órbita do asteróide",
    "PlaceholderFoco1ElipsePlaneta" => "Insira o primeiro foco da elipse do planeta",
    "PlaceholderFoco2ElipsePlaneta" => "Insira o segundo foco da elipse do planeta",
    "BTN_InserirPlaneta" => "Inserir Planeta",
    "BTN_VoltarListaSistemas" => "Voltar à lista de Sistemas",
    "BTN_EditarPlaneta" => "Editar Planeta",
    "BTN_EditarAsteroid" => "Editar Asteroide",
    "TitleEditarPlaneta" => "Editar Planeta",
    //Detalhes evento
    "BTN_VoltarListaEventos" => "Voltar à lista de Eventos",
    "LabelNomeEvento" => "Nome do evento",
    "LabelLatitudeEvento" => "GPS Latitude",
    "LabelLongitudeEvento" => "GPS Longitude",
    "LabelDistânciaPlanetaLonge" => "Distância do planeta mais longe",
    "LabelParticipaçõesEvento" => "Participações",
    "LabelNomeAluno" => "Nome do Aluno",
    "LabelPontos" => "Pontos",
    "LabelData" => "Data",
    "LabelTotalPontos" => "Total de pontos",
    //Editar Eventos e Adicionar Eventos
    "TituloCriarEvento" => "Criar Evento",
    "TituloEditarEvento" => "Editar Evento",
    "PlaceholderNomeEvento" => "Insira o nome do evento",
    "PlaceholderLatitudeEvento" => "Insira a latitude do centro do evento",
    "PlaceholderLongitudeEvento" => "Insira a longitude do centro do evento",
    "PlaceholderDistânciaPlanetaLonge" => "Insira a distância do planeta mais longinquo",
    "BTN_EditarEvento" => "Editar Evento",
    "LabelSistemaUsar" => "Sistema a utilizar",
    "BTN_ParametrizarEvento" => "Parametrizar Evento",
    //Confirmação de email
    "LabelWelcome" => "Bem-vindo,",
    "ConfirmParagrafo1" => "Você precisa de verificar a sua conta.",
    "ConfirmParagrafo2" => "Por favor vá ao seu email e clique no link",
    "ConfirmParagrafo3" => "de verificação que acabámos de lhe enviar para",
    "ConfirmParagrafo4" => "Não recebeu o email de confirmação?",
    "ConfirmParagrafo5" => "Para reenviar, clique no botão abaixo",
    "HyperlinkSendEmail" => "Reenviar email",
    //Apagar planeta
    "AskDeletePlanet" => "Deseja apagar este planeta?",
    "BTN_Return" => "Voltar atrás",
    "BTN_DeletePlanet" => "Apagar Planeta",
    //Apagar Evento
    "AskDeleteEvent" => "Deseja apagar este evento?",
    "BTN_DeleteEvent" => "Apagar Evento",
    //Sobre o jogo
    "TitleAboutGame" => "Sobre o jogo",
    "AboutGameParagrafo1" => "O jogo PlanetarySystemGO tem por objetivo promover a aprendizagem sobre o Sistema Solar de uma forma lúdica, a partir de uma aplicação de Realidade Aumentada (RA) disponível no telemóvel. Neste jogo, os alunos organizados em equipas de 3 a 4 alunos, iniciam a viagem no Sol e o desafio é encontrar as órbitas e os respetivos planetas, respondendo a questões sobre os mesmos. Por cada etapa cumprida com sucesso recebem pontuação e a equipa com mais pontos ganha o jogo.",
    "AboutGameParagrafo2" => "A RA é um tópico emergente que tem vindo a ganhar protagonismo graças ao seu grande potencial para combinar o mundo real com objetos virtuais, o que permite captar o interesse e a atenção dos estudantes de modo a promover a aprendizagem dos mesmos.",
    "AboutGameParagrafo3" => "Para ser jogado, é necessário GPS pelo que tem que decorrer num espaço exterior afastado de edifícios e outros obstáculos que possam prejudicar o recurso ao mesmo.",
    "AboutGameParagrafo4" => "O BackOffice tem por objetivo dar a possibilidade aos professores dos vários graus de ensino de personalizarem este jogo de acordo com o programa que estão a lecionar. Neste sentido, os professores podem, por exemplo, criar as questões que considerem adequadas ao seu nível de ensino.",
    "AboutGameParagrafo5" => "O SolarSystemGO realizado pelos alunos Miguel Silva, Rafael Lopes e Telmo Faria resulta da continuação de um projeto que teve inicio no ano letivo 2016/2017 (Carrança, 2017) em parceria com a Academia da Ciência, Arte e Património.",
    "AboutGameReferencia" => "Referência:",
    "AboutGameTextoReferencia" => "J. A. Carrança, Tecnologias de Realidade Aumentada com Aplicação ao Ensino e Divulgação da Astronomia e da Paleontologia, Master Thesis (in portuguese), Instituto Politécnico de Tomar, 2017.",
    //Criar Sistema    
    "TituloAdicionarSistema" => "Adicionar novo Sistema",
    "LabelNomeSistema" => "Nome do sistema",
    //Editar Sistema
    "TituloEditarSistema" => "Editar Sistema",
    "LabelNovoNome" => "Novo nome:",
    "DataValueRequired" => "O Nome é de preenchimento obrigatório!",
    //Apagar Sistema
    "LabelApagarSistema" => "Tem a certeza que deseja apagar este sistema?",
    "LabelCuidado" => "Atenção! Existem planetas neste sistema!",
    //Lost Password
    "TituloLostPassword" => "Enviar email para repôr password",
    "BTN_EnviarEmail" => "Enviar Email",
    "LabelForgotPassword" => "Esqueceu-se da sua password? Clique",
    "AnchorHere" => "aqui",
    "TitleReporPassword" => "Repôr a sua password",
    "LabelCantUpdatePassword" => "Não foi possível atualizar a password. Por favor tente mais tarde.",
    "LabelSuccessfullPasswordChange" => "A sua password foi alterada com sucesso. Por favor faça login na sua conta.",
    "LabelErrorPasswordChange" => "O link é inválido ou a password já foi mudada.",
    "LabelCantRecoverPassword" => "Neste momento não é possível recuperar a sua password. Por favor, tente mais tarde.",
    "LabelEmailAlreadySent" => "O email de confirmação já foi enviado.",
    "LabelMissingEmailDatabase" => "O email introduzido não se encontra na base de dados.",
    "LabelEmailSendingError" => "Ocorreu um erro a enviar o email de confirmação. Por favor tente mais tarde.",
    "LabelEmailSentSuccessfully" => " Email enviado com sucesso! Por favor vá à sua caixa de correio e clique no link que lhe acabámos de enviar",
    "EmailLostPasswordSubject" => "Recuperação da conta do PlanetarySystemGO",
    "EmailLostP1" => "Para mudar a password da sua conta do PlanetarySystemGO, clique",
    "CantRecoverPW" => "Neste momento não é possível recuperar a sua password. Tente mais tarde",
    "AlreadySentPW" => "Já foi enviado um email.",
    "MessageChangesError" => "Ocorreu um erro ao enviar o email",
    "BadEmailProvided" => "O email que inseriu é inválido!",
    //Perguntas do Planeta      
    "BTN_ReturnPlanetList" => "Voltar à lista de Planetas",
    "LabelAddQuestion" => "Adicionar pergunta",
    "LabelPerguntasPlaneta" => "Perguntas do Planeta: ",
    "LabelQuestion" => "Pergunta",
    "LabelRespostaCorreta" => "Resposta correta",
    "BTN_Edit" => "Editar",
    "BTN_Delete" => "Apagar",
    //Criar Pergunta
    "TitleAddQuestion" => "Adicionar nova pergunta",
    "DataValueRequiredPergunta" => "A Pergunta é de preenchimento obrigatório!",
    "LabelRespostas" => "Respostas",
    "LabelRespostaCerta" => "Certa",
    "DataValueRequiredResposta" => "A resposta é de preenchimento obrigatório!",
    "DataValueRequiredCorreta" => "O Opção certa é de preenchimento obrigatório!",
    "BTN_ReturnListQuestions" => "Voltar à lista de perguntas",
    "BTN_AddQuesion" => "Adicionar",
    //Editar Pergunta
    "TitleEditQuestion" => "Editar Pergunta",
    "QuestionActive" => "Ativa",
    "Save" => "Guardar",
    "GoBack" => "Voltar atrás",
    //Apagar Pergunta
    "LabelAskDelete" => "Quer mesmo apagar esta pergunta?",
    "LabelPerguntaSelecionada" => "Pergunta selecionada:",
    "LavelConfirmarApagar" => "Apagar",
    //Verificar
    "LabelRegistoComSucesso" => "A sua conta foi verificada com sucesso. Pode agora entrar e utilizar todas as funcionalidades do sistema.",
    "LabelRegistoSemSucesso" => "Esta conta é inválida ou já foi verificada.",
    "LabelSemRegisto" => "Ocorreu um erro. Por favor tente mais tarde.",
    //Repositorios
    "DefaultRepo" => "Escolha um repositório",
    "PrivRepo" => "Privado",
    "AgrupRepo" => "Organização",
    "PublicRepo" => "Publico",
    "BTN_Clone" => "Clonar",
    "BTN_Clone_Agrup" => "Clonar para a Organização",
    //myProfile
    "ChangePW" => "Alterar Password",
    "ChangeProfile" => "Alterar Perfil",
    "Alterar_Perfil" => "Submeter",
    //Change Password
    "Alt_PW_CP" => "Password Atual",
    "N_PW_CP" => "Nova Password",
    "C_PW_CP" => "Confirmar Nova Password",
    "MessageChangesSuccess" => "Informações alteradas com sucesso",
    "MessageChangeError" => "Ocorreu um erro!",
    //Organization
    "Non-Existent-Organization" => "Oops! Parece que não está inserido/a numa organização. Deseja criar uma?",
    "BTN_Create_Organization" => "Criar Organização",
    "BTN_ShowSystems" => "Mostrar sistemas da organização",
    "BTN_ShowMembers" => "Mostrar membros da organização",
    "BTN_InviteMembers" => "Convidar utilizadores para a organização",
    "ButtonInviteToOrganization" => "Convidar utilizador",
    "TitleInvite" => "Convidar",
    "PlaceholderInvite" => "Insira o email do utilizador que pretende convidar",
    "ErrorEmailNonExistant" => "O email inserido não se encontra no sistema!",
    "ErrorAlreadyInOrganization" => "Esse utilizador já está numa organização!",
    "EmailSuccessfullySent" => "O email foi enviado com sucesso!",
    "ErrorSendingEmail" => "Ocorreu um erro ao enviar o email!",
    "InviteTitle" => "Convite para a organização ",
    "InviteText1" => "O utilizador ",
    "InviteText2" => " convidou-o para se juntar à sua organização.",
    "InviteText3" => "Se deseja aceitar, clique ",
    "InviteText4" => ", caso contrário, ignore este email.",
    "BTN_RemoveMembers" => "Remover membros da organização",
    "LabelRemoveMember" => "Remover",
    "SuccessfullyRemoved" => "Utilizador removido com sucesso!",
    "ErrorRemoving" => "Ocorreu um erro ao tentar remover o utilizador",
    "NotAdmin" => "Você não é um administrador!",
    "BTNEditOrganization" =>"Editar Organização",
    "AlreadyOrganizationError" => "Você já se encontra numa organização!",
    "InvitationAccepted" => "Convite aceite com sucesso!",
    "InvitationError" => "Ocorreu um erro enquanto tentava aceitar o convite.",
    "OrganizationDeletedMessage" => "Organização apagada com sucesso!",
    "OrganizationDeleteFail" => "Ocorreu um problema enquanto tentava apagar a organização.",
    "OrganizationDeleteQuestion" => "Está prestes a apagar a organização. Tem a certeza que a quer apagar?",
    "OrganizationEditButton" => "Editar Organização",
    "PlaceholderNomeAgrupamento" => "Insira o nome da organização",
    "BTNDeleteOrganization" => "Apagar organização",
    "BTN_RETURN_DELETE_ORG" => "Voltar para trás",
    //Pergunta
    "SelectCorrectQuestion" => "Por favor escolha qual é a resposta correta",
    "OrganizationEditedMessage" => "Organização editada com sucesso!",
    "OrganizationNotEditedMessage" => "Ocorreu um erro na edição da organização. Por favor tente mais tarde.",
    "PlaceholderNewPassword" => "Insira a sua nova password",
    "PlaceholderConfirmNewPassword" => "Insira outra vez a sua nova password",
    "ResetPasswordBTN" => "Repor Password",
    "LabelAdministração" => "Administração",
    "LabelListOfUsers" => "Lista de Utilizadores",
    "LabelListOfSystems" => "Lista de Sistemas",
    "LostPWSent" => "Email enviado com sucesso!",
    "EventAlreadyExists" => "Um evento com o mesmo nome já existe!",
    "LabelRepositorioPublico" => "Repositório Público",
    "LabelRepositorioPrivado" => "Repositório Privado",
    "LabelRepositorioOrganizacao" => "Repositório da Organização",
    "DownloadAPKBTN" => "Descarregar APK",
    "PlanetCreatedSuccessfully" => "Planeta criado com sucesso!",
    "PlanetNotCreated" => "Ocorreu um erro enquanto tentava criar um planeta!",
    "AsteroidCreatedSuccessfully" => "Asteroide criado com sucesso!",
    "AsteroidNotCreated" => "Ocorreu um erro enquanto tentava criar um asteroide!",
    "BTN_GráficosDoEvento" => "Gráficos do Evento",
    "LabelListOfEvents" => "Lista de Eventos",
    //front-end
    "btn_moreRadius" => "Aumentar raio",
    "btn_lessRadius" => "Diminuir radio",
    "btn_moreSpeed" => "Aumentar velocidade",
    "btn_lessSpeed" => "Diminuir velocidade",
    "btn_moreSize" => "Aumentar tamanho",
    "btn_lessSize" => "Diminuir tamanho",
    "btn_details" => "Mais detalhes",
    "btn_changeCenter" => "Mudar o centro",
    "btn_Send" => "Aceitar sistema",
    "PlanetDeletedSuccessfully" => "Planeta removido",
    "PlanetNotDeleted" => "Planeta não removido",
    "PlaceholderNomeAsteroid" => "Insira o nome do Asteroide",
    "LabelImagemAsteroid" => "Imagem Asteroide",
    "LabelTexturaAsteroid" => "Textura Asteroide",
    "PlaceholderDescriçãoAsteroid" => "Inserir a descrição do asteroide",
    "PlaceholderTamanhoAsteroid" => "Inserir o tamanho do asteroide",
    "PlaceholderVelocidadeAsteroid" => "Insira a velocidade do asteroide",
    "PlaceholderVelocidadeRotaçãoAsteroid" => "Insira a velocidade de rotação do asteroide",
    "BTN_InserirAsteroid" => "Inserir Asteroide",
    //Criar Luas
    "PlaceholderNomeLuas" => "Insira o nome da Lua",
    "LabelImagemLuas" => "Imagem Lua",
    "LabelTexturaLuas" => "Textura Lua",
    "PlaceholderDescriçãoLuas" => "Inserir a descrição da lua",
    "PlaceholderTamanhoLuas" => "Inserir o tamanho da lua",
    "PlaceholderVelocidadeLuas" => "Insira a velociade da lua",
    "PlaceholderVelocidadeRotaçãoLuas" => "Insira a velociade de rotação da lua",
    "BTN_InserirLua" => "Inserir lua",
    "luasCreatedSuccessfully" => "Lua criada com sucesso!",
    "luasNotCreated" => "Existiu um erro ao criar a lua!",
    "BTN_CriarLua" => "Criar Lua",
    "LabelDistanciaFoco1ElipseOrbitamoon" => "Distância do Primeiro Foco da Órbita da Lua",
    "LabelDistanciaFoco2ElipseOrbitamoon" => "Distância do Segundo Foco da Órbita da Lua",
    "BTN_EditarLua" => "Editar Lua",
    "BTN_ApagarLua" => "Apagar Lua",
    "LuasNotDeleted" => "Lua não removida",
    "LuasDeletedSuccessfully" => "Lua removida",
    "AskDeleteMoon" => "Deseja apagar esta lua?",
    //Perguntas Luas
    "BTN_PerguntaLua" => "Pergunta sobre a lua",
    "LabelPerguntasLua" => "Perguntas da lua: ",
    "LabelAddQuestion" => "Adicionar pergunta",
    "PesquisarCorpoCeleste" => "Pesquisar Corpo Celeste",
    "Pesquisar" => "Pesquisar",
    "LimparPesquisa" => "Limpar pesquisa",
    "LuasAssociadas" => "Luas Associadas"
);